spring:
  application:
    name: irctc-api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

management:
  tracing:
    sampling:
      probability: 1.0