spring:
  data:
    mongodb:
      username: irctc
      password: password
      host: localhost
      port: 27017
      database: irctc_customer
      authentication-database: admin

server:
  port: 8090