version: '3.8'

services:
  database:
      image: postgres:15
      container_name: postgres_db
      ports:
        - '25432:5432'
      environment:
        POSTGRES_USER: admin 
        POSTGRES_PASSWORD: password 
        POSTGRES_DB: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: