version: "3.8"

services:
  database:
    image: postgres:15
    container_name: postgres_db
    # ports:
    #   - "25432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis_db
    # ports:
    #   - "6379:6379"
    networks:
      - app-network

  irctc-be:
    build: .
    container_name: irctc-be
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=admin
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
      - redis
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
