spring:
  profiles:
    active: native
  application:
    name: irctc_config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

server:
  port: 8888
