spring:
  data:
    mongodb:
      username: irctc
      password: password
      host: localhost
      port: 27017
      database: irctc_customer
      authentication-database: admin
  cloud:
    discovery:
      enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: trainSeatBookingGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: trainSeatBookingConfirmation:com.harshchauhan.irctc_notification_email.kafka.dto.TrainSeatBookingConfirmationDto
  mail:
    host: localhost
    port: 1025
    username: irctc_temp
    password: irctc_temp
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8092
